---
- hosts: web
  vars:
    root_dir: /var/www/html
    conf_dir: /etc/nginx
    nginx_port: 80

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
      tags: nginx
    
    - name: added index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      tags: file

    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf
        dest: "{{conf_dir}}/nginx.conf.j2"
      notify:
        - restart nginx
      become: yes
      tags: file1
 
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
      tags: rell

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes  