---
# tasks file for install_nginx
- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
  become: yes
  tags: nginx
    
- name: added index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{root_dir}}/index.html"
  tags: file

- name: update nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{conf_dir}}/nginx.conf"
  notify:
    - restart nginx
  become: yes
  tags: config
 
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: yes
  tags: relload
